const NAMESPACE_MUI = 'REACT_DASHBOARD_MUI_';

const actions = {
  LOGIN_USER: `${NAMESPACE_MUI}LOGIN_USER`,
  LOGIN_USER_SUCCESSFUL: `${NAMESPACE_MUI}LOGIN_USER_SUCCESSFUL`,
  LOGIN_USER_FAILED: `${NAMESPACE_MUI}LOGIN_USER_FAILED`,
  LOGOUT_USER: `${NAMESPACE_MUI}LOGOUT_USER`,
};

export default actions;